### ISSUE TITLE
vertical line

### ISSUE THREAD

**Issue by outflux3** [owzim/pw-inputfield-ace-extended#4]
running the latest dev version of this module and all looks good; 
only one minor issue i have is there is light vertical line through the editor field; so far only tested on firefox; will try and post screenshot

**Comment by owzim** [comment]
This line is called `printMargin` ([see docs](http://ace.c9.io/api/virtual_renderer.html)), you can change the settings in the advanced options on your field settings input tab:

``` JSON
{
  "showPrintMargin": false,
  "printMarginColumn": true,
  "printMargin" : 80
}
```
